### ISSUE TITLE
Warn when required environment variables are missing

### ISSUE THREAD

**Issue by ghost** [dnsimple/coredns-dnsimple#20]
Currently, if DNSIMPLE_TOKEN and/or DNSIMPLE_ACCOUNT_ID are not provided, we simply silently proceed, which will lead to less friendly errors around API failures. We should instead check that these exist and fail if they haven't been provided in the config or env vars.

**Comment by DXTimer** [comment]
Agree. We should only check and error if the corresponding config options are missing.
