### ISSUE TITLE
Optionally allow disabling status updates

### ISSUE THREAD

**Issue by wilson-dnsimple** [dnsimple/coredns-dnsimple#22]
For advanced users who don't need or want the automatic status updates, it should be possible to turn off the feature if requested. For example, they may already have their own logging, monitoring, and alerting set up, and would prefer not to duplicate such functionality.

**Comment by DXTimer** [comment]
I would prefer to give the ability to disable alerting in the app rather than altogether losing visibility, since we are not just monitoring if integration is up/down but also if there are any zone issues, such as broken records.
